### ISSUE TITLE
Allow configurable amount of attempts at login:

### ISSUE THREAD

**Issue by SJCaldwell** [CyberNinjas/pam_aad#2]
How many attempts does a user get to have a successful login before they are rejected?

Debian defaults to 3, I believe, and then will terminate the connection.

UPDATE: standard unix authentication uses 3. The pam module allows 6 currently, without my having set any options in-particular.

**Comment by Jnchi** [comment]
> This module maintains a count of attempted accesses, can reset count on success, can deny access if too many attempts fail.
--[pam_tally2 - login counter (tallying) module](http://linux-pam.org/Linux-PAM-html/sag-pam_tally2.html)

**Update:**

This can also be configured in OpenSSH via `/etc/ssh/sshd_config`:

```
StrictModes yes
MaxAuthTries 3

# Other helpful options
#MaxSessions 2
#LoginGraceTime 2m
```

No need to reinvent this functionality, closing.
