### ISSUE TITLE
Abandon key.pem file to on-the-fly key validation

### ISSUE THREAD

**Issue by SJCaldwell** [CyberNinjas/pam_aad#4]
Static keys don't allow for rolling changes with Microsoft's public key.

> It is important to note that these keys rollover on a periodic basis and, in an emergency, could be rolled over immediately. All applications that use Azure AD should be able to programmatically handle the key rollover process or establish a periodic manual rollover process.

As Microsoft states [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-signing-key-rollover), those applications that roll their own API interaction instead of using a supported azure library will have to be wary to update public keys.

As a security-critical application, we cannot afford to have a static key that needs updating. 

We must be able to poll Microsoft's key repository to ensure our key is up-to-date. I used a node library to convert the jwk to a pem file that openssl could use for validation previously, but I'll have to do it in C code (`int jwk_to_pem_rsa(cJSON jwk){...}`) instead.

**Comment by Jnchi** [comment]
> Static keys don't allow for rolling changes with Microsoft's public key.
> 
> > It is important to note that these keys rollover on a periodic basis and, in an emergency, could be rolled over immediately. All applications that use Azure AD should be able to programmatically handle the key rollover process or establish a periodic manual rollover process.
> 
> As Microsoft states [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-signing-key-rollover), those applications that roll their own API interaction instead of using a supported azure library will have to be wary to update public keys.
> 
> As a security-critical application, we cannot afford to have a static key that needs updating.
> 
> We must be able to poll Microsoft's key repository to ensure our key is up-to-date. I used a node library to convert the jwk to a pem file that openssl could use for validation previously, but I'll have to do it in C code (`int jwk_to_pem_rsa(cJSON jwk){...}`) instead.

`aadd` - _Azure Active Directory Daemon?_

Source: [`src/getkeys.c`](https://github.com/CyberNinjas/pam_aad/blob/e681411ee039f25ff650d0e4bdccc452834ad443/src/getkeys.c)

See also: [`pam_ftp`](https://github.com/linux-pam/linux-pam/tree/master/modules/pam_ftp), [`pam_mkhomedir`](https://github.com/linux-pam/linux-pam/tree/master/modules/pam_mkhomedir), [`pam_userdb`](https://github.com/linux-pam/linux-pam/tree/master/modules/pam_userdb)

[LDAP authentication using pam_ldap and nss_ldap](http://www.tldp.org/HOWTO/archived/LDAP-Implementation-HOWTO/pamnss.html)

[Simple example of daemon for Linux (GitHub)](https://github.com/jirihnidek/daemon)

**Comment by Jnchi** [comment]
> Static keys don't allow for rolling changes with Microsoft's public key.
> 
> > It is important to note that these keys rollover on a periodic basis and, in an emergency, could be rolled over immediately. All applications that use Azure AD should be able to programmatically handle the key rollover process or establish a periodic manual rollover process.
> 
> As Microsoft states [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-signing-key-rollover), those applications that roll their own API interaction instead of using a supported azure library will have to be wary to update public keys.
> 
> As a security-critical application, we cannot afford to have a static key that needs updating.
> 
> We must be able to poll Microsoft's key repository to ensure our key is up-to-date. I used a node library to convert the jwk to a pem file that openssl could use for validation previously, but I'll have to do it in C code (`int jwk_to_pem_rsa(cJSON jwk){...}`) instead.

`aadd` - _Azure Active Directory Daemon?_

**Comment by Jnchi** [comment]
https://www.openstack.org/videos/vancouver-2018/federated-keystone-single-sign-on-with-freeipa-and-openid-connect

**Comment by Jnchi** [comment]
https://github.com/openstack/keystone

**Comment by Jnchi** [comment]
https://github.com/CyberNinjas/pam_useradd
